apps/index/urls.py
from django.urls import path

from . import views


app_name = 'index'
urlpatterns = [
    path('', views.index, name='index'),
    path('spelling_correction', views.spell, name='parse')
]

apps/lang_model/urls.py
from django.urls import path

from . import views


app_name = 'lang_model'
urlpatterns = [
    path('', views.index, name='index'),
]

apps/min_edit_dist/urls.py
from django.urls import path

from . import views


app_name = 'min_edit_dist'
urlpatterns = [
    path('', views.index, name='index'),
    path('levenshtein_table', views.min_edit_table, name='table'),
    path('find_close_word/', views.close_word, name='close_word'),
]

apps/morphology_parser/urls.py
from django.urls import path

from . import views


app_name = 'morphology_parser'
urlpatterns = [
    path('', views.index, name='index'),
    path('', views.index, name='parse'),
]

nlp_amaceh/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.index.urls')),
    path('morphology/', include('apps.morphology_parser.urls')),
    path('minimum_edit_distance/', include('apps.min_edit_dist.urls')),
    path('language_model/', include('apps.lang_model.urls')),
    path('admin/', admin.site.urls),

]

apps/index/templates/index/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}ILKOM NLP</title>
    {% include 'index/layout/header.html' %}
    {% block extra_style %}{% endblock %}
</head>
<body>
<!-- Include Navbar -->
{% include 'index/layout/navbar.html' %}
<!-- Page Content -->
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8">
                <br>
    <!-- Blog Post -->
    <div class="card mb-4">
        <div class="card-body">
            <h2 class="card-title">{% block text-title %}{% endblock text-title %}</h2>
            <p class="card-text">{% block content %}{% endblock content %}</p>
            <!--<a href="" class="btn btn-primary">Read More</a>-->
        </div>
        <div class="card-footer text-muted">
            Last Updated on {% block date %}{% endblock date %}
            <!--by-->
            <!--<a href="#">xxx</a>-->
        </div>
    </div>


        </div>
        {% include 'index/layout/sidebar.html'%}
    </div>
    <!-- /.row -->
</div>
<!-- /.container -->
{% include 'index/layout/footer.html'%}
{% block extra_script %}{% endblock extra_script %}
<!-- -->
</body>
</html>

apps/index/templates/index/layout/footer.html
{% load static %}
<!-- Footer -->
<!--<footer class="py-2 bg-dark">-->
    <!--<div class="container">-->
        <!--<p class="m-0 text-center text-white">Copyright &copy; Amaceh & Bisma 2018</p>-->
    <!--</div>-->
    <!--&lt;!&ndash; /.container &ndash;&gt;-->
<!--</footer>-->


<!-- jQuery CDN -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<!-- jQuery local fallback -->
<script>
    window.jQuery || document.write('<script src="{% static 'index/bootstrap/js/jquery-3.3.1.slim.min.js' %}"><\/script>')
</script>
<!-- Bootstrap JS CDN -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
        integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>
<!-- Bootstrap JS local fallback -->
<script>
    if(typeof($.fn.modal) === 'undefined') {document.write('<script src="{% static 'index/bootstrap/js/bootstrap.min.js' %}"><\/script>')}
</script>
<!-- Bootstrap CSS local fallback -->
<div id="bootstrapCssTest" class="hidden"></div>
<script>
    $(function() {
    //   if ($('#bootstrapCssTest').is(':visible')) {
      if(! $.fn.modal){
        $("head").prepend('<link rel="stylesheet" href="{% static 'index/bootstrap/css/bootstrap.min.css' %}">');
      }
    });

</script>

apps/index/templates/index/layout/header.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
{% load static %}
<!-- Custom styles for this template -->
<link rel="stylesheet" type="text/css" href="{% static 'index/style.css' %}"/>
<link rel="shortcut icon" type="image/png" href="{% static 'favicon/favicon.ico' %}" />

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="NLP ILKOM UPI">
<meta name="author" content="Achmad Abdul Rofiq & Bisma Wahyu">

apps/index/templates/index/layout/navbar.html
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index:index' %}">NLP Ilkom UPI</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index:index' %}">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
                <!--<li class="nav-item">-->
                    <!--<a class="nav-link" href="#">Services</a>-->
                <!--</li>-->
                <!--<li class="nav-item">-->
                    <!--<a class="nav-link" href="#">Contact</a>-->
                <!--</li>-->
            </ul>
        </div>
    </div>
</nav>

apps/index/templates/index/layout/sidebar.html
        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">
            <!--TODO search widget-->
            <!-- Search Widget -->
            <!--<div class="card my-4">-->
                <!--<h5 class="card-header">Search</h5>-->
                <!--<div class="card-body">-->
                    <!--<div class="input-group">-->
                        <!--<input type="text" class="form-control" placeholder="Search for...">-->
                        <!--<span class="input-group-btn">-->
                  <!--<button class="btn btn-secondary" type="button">Go!</button>-->
                <!--</span>-->
                    <!--</div>-->
                <!--</div>-->
            <!--</div>-->

            <!-- Categories Widget -->
            <div class="card my-4">
                <h5 class="card-header">Categories</h5>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <ul class="list-unstyled mb-0">
                                <li>
                                    <a href="{% url 'morphology_parser:index' %}">Morphological Parser</a>
                                </li>
                                <li>
                                    <a href="{% url 'min_edit_dist:index' %}">Minimun Edit Distance</a>
                                </li>
                                <li>
                                    <a href="{% url 'lang_model:index' %}">Language Model</a>
                                </li>
                                <li>
                                    <a href="{% url 'index:parse' %}">Spelling Correction</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="card my-4">
                <h5 class="card-header">Repositories</h5>
                <div class="card-body">
                    This Source is available at Gitlab <a href="https://gitlab.com/amaceh/nlp-ilkom">https://gitlab.com/amaceh/nlp-ilkom</a>
                    please report bug and issue there. Enjoy :)
                </div>
            </div>

        </div>